customhost = "employee.cmackuxhlc18.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "yeongyikshen-employee"
customregion = "us-east-1"
